# Generated by Django 3.2.14 on 2022-08-01 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50, verbose_name='Name of the company')),
                ('position', models.CharField(max_length=50, verbose_name='Position of the user')),
                ('start_date', models.DateField(verbose_name='The date when the user started working')),
                ('end_date', models.DateField(default=None, verbose_name='The date when the user ended working')),
                ('work_description', models.CharField(default=None, max_length=250, verbose_name='Brief work description')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Name of the user')),
            ],
            options={
                'ordering': ['end_date'],
            },
        ),
    ]
