# Generated by Django 3.2.14 on 2022-08-01 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workexperience',
            name='end_date',
            field=models.DateField(blank=True, default=None, verbose_name='The date when the user ended working'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='work_description',
            field=models.CharField(blank=True, default=None, max_length=250, verbose_name='Brief work description'),
        ),
    ]
