# Generated by Django 3.2.14 on 2022-08-01 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220801_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workexperience',
            name='end_date',
            field=models.DateField(default=None, null=True, verbose_name='The date when the user ended working'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='work_description',
            field=models.CharField(default=None, max_length=250, null=True, verbose_name='Brief work description'),
        ),
    ]
