# Generated by Django 3.2.15 on 2022-08-26 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20220826_0619'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='speciality_en_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Specialty EN'),
        ),
        migrations.AddField(
            model_name='education',
            name='speciality_en_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Specialty EN'),
        ),
    ]
