# Generated by Django 3.2.15 on 2022-08-26 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20220826_0957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='course_description',
        ),
        migrations.RemoveField(
            model_name='education',
            name='speciality_en_en',
        ),
        migrations.RemoveField(
            model_name='education',
            name='speciality_en_ru',
        ),
        migrations.AddField(
            model_name='education',
            name='course_description_en',
            field=models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Brief course description EN'),
        ),
        migrations.AddField(
            model_name='education',
            name='course_description_ru',
            field=models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Brief course description RU'),
        ),
    ]
