# Generated by Django 3.2.15 on 2022-08-26 11:42

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20220826_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='skills',
            field=django.contrib.postgres.fields.jsonb.JSONField(default='[]', verbose_name='Users skills'),
        ),
    ]
