# Generated by Django 3.2.15 on 2022-08-26 11:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_user_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AddField(
            model_name='user',
            name='name_en',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='Users name EN'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='name_ru',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='Users name RU'),
            preserve_default=False,
        ),
    ]
