# Generated by Django 3.2.15 on 2022-08-26 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20220826_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='surname_en',
            field=models.CharField(default='aa', max_length=50, verbose_name='Users surname EN'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='surname_ru',
            field=models.CharField(default='cc', max_length=50, verbose_name='Users surname RU'),
            preserve_default=False,
        ),
    ]
