# Generated by Django 3.2.15 on 2022-08-26 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20220826_1227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.AddField(
            model_name='user',
            name='address_en',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Address EN'),
        ),
        migrations.AddField(
            model_name='user',
            name='address_ru',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Address RU'),
        ),
        migrations.AlterField(
            model_name='user',
            name='experience',
            field=models.CharField(choices=[('no', 'No experience'), ('1', 'Less than 1 year'), ('12', 'From 1 to 2 years'), ('23', 'From 1 to 3 years'), ('3', 'More than 3 years')], default='aa', max_length=50, verbose_name='Experience'),
            preserve_default=False,
        ),
    ]
