# Generated by Django 3.2.15 on 2022-08-27 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20220826_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name_en',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Users name EN'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name_ru',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Users name RU'),
        ),
        migrations.AlterField(
            model_name='user',
            name='skills',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Users skills'),
        ),
        migrations.AlterField(
            model_name='user',
            name='surname_en',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Users surname EN'),
        ),
        migrations.AlterField(
            model_name='user',
            name='surname_ru',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Users surname RU'),
        ),
    ]
